---
title: NTNU GradeInsight
author: Øyvind Klåpbakken
date: '2019-06-04'
slug: ntnu-grade-insight
categories: []
tags: []
description: 'A web app that provides insight into your academic performance at NTNU.'
externalLink: ''
series: []
---

NTNU GradeInsight is an app that is intended to provide NTNU students with more insight into their academic performance. I, and many others, feel that the the conventional grading system is very inconsistent and that your actual performance in a course can't be communicated in an honest way by using a single letter grade. NTNU GradeInsight allows student to upload their grades and get detailed information about how their performance compares to their fellow students. This is done by showing the students their "grade percentile", i.e. how many of their peers they either matched or were better than. This is calculated using official grade statistic provided by NTNU.

The web app can be accessed [here](https://klaapbakken.shinyapps.io/GradeInsight/). The source code can be found the assosciated [Github repository](https://github.com/klaapbakken/ntnu-gradeinsight). 

I intend to add more functionality to the app in the coming months. Check back for more!